Models/Gallery.cs
using System.ComponentModel.DataAnnotations;

namespace GharchNews.Models
{
    public class Gallery
    {
        [Key]
        public int GalleryId { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد نمایید")]
        [Display(Name = "نام گالری")]
        [MaxLength(50)]
        public string GalleryName { get; set; } = default!;

        [Display(Name = "توضیح مختصر")]
        [MaxLength(300)]
        public string? Description { get; set; }
        public virtual List<Image>? Images { get; set; }
    }
}

Pages/Admin/Gallery/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Gallery
{
    public class CreateModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public CreateModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Models.Gallery Gallery { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Galleries.Add(Gallery);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Gallery/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Gallery
{
    public class DeleteModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public DeleteModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Gallery Gallery { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Gallery = await _context.Galleries.FirstOrDefaultAsync(m => m.GalleryId == id);

            if (Gallery == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Gallery = await _context.Galleries.FindAsync(id);
            if (Gallery != null)
            {
                _context.Galleries.Remove(Gallery);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Gallery/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Gallery
{
    public class EditModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public EditModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Gallery Gallery { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Gallery =  await _context.Galleries.FirstOrDefaultAsync(m => m.GalleryId == id);
            if (Gallery == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Gallery).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GalleryExists(Gallery.GalleryId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool GalleryExists(int id)
        {
            return _context.Galleries.Any(e => e.GalleryId == id);
        }
    }
}

Pages/Admin/Gallery/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Gallery
{
    public class IndexModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public IndexModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Models.Gallery> Gallery { get;set; } = default!;

        public async Task OnGetAsync()
        {
            Gallery = await _context.Galleries.ToListAsync();
        }
    }
}

Pages/Admin/Hashtag/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Hashtag
{
    public class CreateModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public CreateModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Models.Hashtag Hashtag { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Hashtags.Add(Hashtag);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Hashtag/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Hashtag
{
    public class DeleteModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public DeleteModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Hashtag Hashtag { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Hashtag = await _context.Hashtags.FirstOrDefaultAsync(m => m.HashtagId == id);

            if (Hashtag == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Hashtag = await _context.Hashtags.FindAsync(id);
            if (Hashtag != null)
            {
                _context.Hashtags.Remove(Hashtag);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Hashtag/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Hashtag
{
    public class EditModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public EditModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Hashtag Hashtag { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Hashtag =  await _context.Hashtags.FirstOrDefaultAsync(m => m.HashtagId == id);
            if (Hashtag == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Hashtag).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!HashtagExists(Hashtag.HashtagId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool HashtagExists(int id)
        {
            return _context.Hashtags.Any(e => e.HashtagId == id);
        }
    }
}

Pages/Admin/Image/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using GharchNews.Data;
using GharchNews.Models;
using Microsoft.EntityFrameworkCore;

namespace GharchNews.Pages.Admin.Image
{
    public class CreateModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public CreateModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            ViewData["GalleryId"] = new SelectList(_context.Galleries, "GalleryId", "GalleryName");
            return Page();
        }

        [BindProperty]
        public Models.Image Image { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD

        public List<IFormFile> imgUp { get; set; } = default!;

        public async Task<IActionResult> OnPostAsync(int GalleryId)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var GalleryName = await _context.Galleries
                .Where(g => g.GalleryId == GalleryId)
                .Select(g => g.GalleryName).FirstOrDefaultAsync();

            if (imgUp != null)
            {
                string SaveDir = "wwwroot/Img/galleryImages/" + GalleryName;
                if (!Directory.Exists(SaveDir))
                    Directory.CreateDirectory(SaveDir);

                foreach (var file in imgUp)
                {
                    string img = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string savePath = Path.Combine(Directory.GetCurrentDirectory(), SaveDir, img);
                    using (var FileSream = new FileStream(savePath, FileMode.Create))
                    {
                        file.CopyTo(FileSream);
                    }

                    Image = new Models.Image
                    {
                        ImageName = img,
                        CreateDate = DateTime.Now,
                        GalleryId = GalleryId,
                        Gallery = Image.Gallery
                    };

                    _context.Images.Add(Image);

                }
            }

            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Image/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Image
{
    public class DeleteModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public DeleteModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Image Image { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Image = await _context.Images.FirstOrDefaultAsync(m => m.ImageId == id);

            if (Image == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Image = await _context.Images.FindAsync(id);
            if (Image != null)
            {
                _context.Images.Remove(Image);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Image/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Image
{
    public class IndexModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public IndexModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Models.Image> Images { get; set; } = default!;
        public Models.Image Image { get; set; } = default!;

        public async Task OnGetAsync()
        {
            ViewData["Galleries"] = await _context.Galleries.Select(g => g.GalleryName).ToListAsync();

            Images = await _context.Images
                .Include(i => i.Gallery).ToListAsync();
        }

        public async Task OnGetGallery(string GalleryName)
        {
            ViewData["CurrentGallery"] = GalleryName;

            Images = await _context.Images
                .Include(i => i.Gallery)
                .Where(i => i.Gallery.GalleryName == GalleryName)
                .OrderByDescending(i => i.CreateDate).ToListAsync();
        }

        public async Task<IActionResult> OnGetDelete(int? id, string? ReturnUrl)
        {
            if (id == null)
            {
                return NotFound();
            }

            Image = await _context.Images.FindAsync(id);

            var galleryName = await _context.Images
                .Where(i => i.ImageId == id)
                .Select(g => g.Gallery.GalleryName)
                .FirstOrDefaultAsync();

            if (Image != null)
            {
                if (Image.ImageName != null)
                {
                    string deletePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Img/GalleryImages/" + galleryName, Image.ImageName);
                    if (System.IO.File.Exists(deletePath))
                        System.IO.File.Delete(deletePath);
                }

                _context.Images.Remove(Image);
                await _context.SaveChangesAsync();
            }

            if (ReturnUrl == null)
            {
                return RedirectToPage("./Index");
            }
            else
            {
                return LocalRedirect("~/Admin/Image?GalleryName=" + ReturnUrl + "&handler=Gallery");
            }

        }

    }
}

Pages/Admin/Gallery/Create.cshtml
@page
@model GharchNews.Pages.Admin.Gallery.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Gallery.GalleryName" class="control-label"></label>
                <input asp-for="Gallery.GalleryName" class="form-control" />
                <span asp-validation-for="Gallery.GalleryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gallery.Description" class="control-label"></label>
                <input asp-for="Gallery.Description" class="form-control" />
                <span asp-validation-for="Gallery.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="افزودن" class="btn btn-primary" />
                <a asp-page="Index" class="btn btn-default">بازگشت به لیست</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Admin/Gallery/Delete.cshtml
@page
@model GharchNews.Pages.Admin.Gallery.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}

<h5 class="alert alert-danger"> آیا از حذف این دسته خبری مطمئن هستید؟ </h5>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gallery.GalleryName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gallery.GalleryName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gallery.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gallery.Description)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" asp-for="Gallery.GalleryId" />
        <input type="submit" value="حذف" class="btn btn-danger" />
        <a asp-page="./Index" class="btn btn-default"> بازگشت به لیست </a>
    </form>
</div>

Pages/Admin/Gallery/Edit.cshtml
@page
@model GharchNews.Pages.Admin.Gallery.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Gallery.GalleryId" />
            <div class="form-group">
                <label asp-for="Gallery.GalleryName" class="control-label"></label>
                <input asp-for="Gallery.GalleryName" class="form-control" />
                <span asp-validation-for="Gallery.GalleryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gallery.Description" class="control-label"></label>
                <input asp-for="Gallery.Description" class="form-control" />
                <span asp-validation-for="Gallery.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="ویرایش" class="btn btn-warning" />
                <a asp-page="./Index" class="btn btn-default"> بازگشت به لیست </a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Admin/Gallery/Index.cshtml
@page
@model GharchNews.Pages.Admin.Gallery.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}

<hr />
<p>
    <a asp-page="Create" class="btn btn-success"> افزودن گالری تصاویر </a>
</p>
<hr />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Gallery[0].GalleryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gallery[0].Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Gallery)
        {
            <tr>
                <td>
                    <a asp-page="../Image/Index" asp-route-GalleryName="@item.GalleryName" asp-page-handler="Gallery">
                        @Html.DisplayFor(modelItem => item.GalleryName)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-page="Edit" asp-route-id="@item.GalleryId"><i class="fa fa-edit" style="color:darkorange;font-size:20px"></i></a>
                    <a asp-page="Delete" asp-route-id="@item.GalleryId"><i class="fa fa-trash" style="color:red;font-size:20px"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>