Pages/Admin/Gallery/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Gallery
{
    public class CreateModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public CreateModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Models.Gallery Gallery { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Galleries.Add(Gallery);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Gallery/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Gallery
{
    public class DeleteModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public DeleteModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Gallery Gallery { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Gallery = await _context.Galleries.FirstOrDefaultAsync(m => m.GalleryId == id);

            if (Gallery == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Gallery = await _context.Galleries.FindAsync(id);
            if (Gallery != null)
            {
                _context.Galleries.Remove(Gallery);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Gallery/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Gallery
{
    public class EditModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public EditModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Gallery Gallery { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Gallery =  await _context.Galleries.FirstOrDefaultAsync(m => m.GalleryId == id);
            if (Gallery == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Gallery).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GalleryExists(Gallery.GalleryId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool GalleryExists(int id)
        {
            return _context.Galleries.Any(e => e.GalleryId == id);
        }
    }
}

Pages/Admin/Hashtag/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Hashtag
{
    public class CreateModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public CreateModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Models.Hashtag Hashtag { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Hashtags.Add(Hashtag);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Hashtag/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Hashtag
{
    public class DeleteModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public DeleteModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Hashtag Hashtag { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Hashtag = await _context.Hashtags.FirstOrDefaultAsync(m => m.HashtagId == id);

            if (Hashtag == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Hashtag = await _context.Hashtags.FindAsync(id);
            if (Hashtag != null)
            {
                _context.Hashtags.Remove(Hashtag);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Hashtag/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Hashtag
{
    public class EditModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public EditModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Hashtag Hashtag { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Hashtag =  await _context.Hashtags.FirstOrDefaultAsync(m => m.HashtagId == id);
            if (Hashtag == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Hashtag).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!HashtagExists(Hashtag.HashtagId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool HashtagExists(int id)
        {
            return _context.Hashtags.Any(e => e.HashtagId == id);
        }
    }
}

Pages/Admin/Image/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using GharchNews.Data;
using GharchNews.Models;
using Microsoft.EntityFrameworkCore;

namespace GharchNews.Pages.Admin.Image
{
    public class CreateModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public CreateModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            ViewData["GalleryId"] = new SelectList(_context.Galleries, "GalleryId", "GalleryName");
            return Page();
        }

        [BindProperty]
        public Models.Image Image { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD

        public List<IFormFile> imgUp { get; set; } = default!;

        public async Task<IActionResult> OnPostAsync(int GalleryId)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var GalleryName = await _context.Galleries
                .Where(g => g.GalleryId == GalleryId)
                .Select(g => g.GalleryName).FirstOrDefaultAsync();

            if (imgUp != null)
            {
                string SaveDir = "wwwroot/Img/galleryImages/" + GalleryName;
                if (!Directory.Exists(SaveDir))
                    Directory.CreateDirectory(SaveDir);

                foreach (var file in imgUp)
                {
                    string img = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    string savePath = Path.Combine(Directory.GetCurrentDirectory(), SaveDir, img);
                    using (var FileSream = new FileStream(savePath, FileMode.Create))
                    {
                        file.CopyTo(FileSream);
                    }

                    Image = new Models.Image
                    {
                        ImageName = img,
                        CreateDate = DateTime.Now,
                        GalleryId = GalleryId,
                        Gallery = Image.Gallery
                    };

                    _context.Images.Add(Image);

                }
            }

            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Image/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Image
{
    public class DeleteModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public DeleteModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Image Image { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Image = await _context.Images.FirstOrDefaultAsync(m => m.ImageId == id);

            if (Image == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Image = await _context.Images.FindAsync(id);
            if (Image != null)
            {
                _context.Images.Remove(Image);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Image/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Image
{
    public class IndexModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public IndexModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Models.Image> Images { get; set; } = default!;
        public Models.Image Image { get; set; } = default!;

        public async Task OnGetAsync()
        {
            ViewData["Galleries"] = await _context.Galleries.Select(g => g.GalleryName).ToListAsync();

            Images = await _context.Images
                .Include(i => i.Gallery).ToListAsync();
        }

        public async Task OnGetGallery(string GalleryName)
        {
            ViewData["CurrentGallery"] = GalleryName;

            Images = await _context.Images
                .Include(i => i.Gallery)
                .Where(i => i.Gallery.GalleryName == GalleryName)
                .OrderByDescending(i => i.CreateDate).ToListAsync();
        }

        public async Task<IActionResult> OnGetDelete(int? id, string? ReturnUrl)
        {
            if (id == null)
            {
                return NotFound();
            }

            Image = await _context.Images.FindAsync(id);

            var galleryName = await _context.Images
                .Where(i => i.ImageId == id)
                .Select(g => g.Gallery.GalleryName)
                .FirstOrDefaultAsync();

            if (Image != null)
            {
                if (Image.ImageName != null)
                {
                    string deletePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Img/GalleryImages/" + galleryName, Image.ImageName);
                    if (System.IO.File.Exists(deletePath))
                        System.IO.File.Delete(deletePath);
                }

                _context.Images.Remove(Image);
                await _context.SaveChangesAsync();
            }

            if (ReturnUrl == null)
            {
                return RedirectToPage("./Index");
            }
            else
            {
                return LocalRedirect("~/Admin/Image?GalleryName=" + ReturnUrl + "&handler=Gallery");
            }

        }

    }
}

Pages/Admin/Report/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GharchNews.Data;
using GharchNews.Models;

namespace GharchNews.Pages.Admin.Report
{
    public class DeleteModel : PageModel
    {
        private readonly GharchNews.Data.ApplicationDbContext _context;

        public DeleteModel(GharchNews.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Models.Report Report { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Report = await _context.Reports.Include(g=>g.ReportGroup).FirstOrDefaultAsync(m => m.ReportId == id);

            if (Report == null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Report = await _context.Reports.FindAsync(id);
            if (Report != null)
            {
                if (Report.Image != null)
                {
                    string deletePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Img/ReportImages", Report.Image);
                    if (System.IO.File.Exists(deletePath))
                        System.IO.File.Delete(deletePath);
                }

                _context.Reports.Remove(Report);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Admin/Image/Create.cshtml
@page
@model GharchNews.Pages.Admin.Image.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Image.ImageName" class="control-label"></label>
                <input asp-for="imgUp" type="file" name="imgUp" multiple id="imgUpload" /> <br />
                <img id="imgpreview" style="max-width:320px" /> <br />
                <span asp-validation-for="Image.ImageName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image.GalleryId" class="control-label"></label>
                <select asp-for="Image.GalleryId" name="GalleryId" class="form-control" asp-items="ViewBag.GalleryId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="افزودن" class="btn btn-primary" />
                <a asp-page="Index" class="btn btn-default">بازگشت به لیست</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}


    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#imgpreview').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#imgUpload").change(function () {
            readURL(this);
        });
    </script>

}

Pages/Admin/Image/Delete.cshtml
@page
@model GharchNews.Pages.Admin.Image.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}

<h5 class="alert alert-danger"> آیا از حذف این دسته خبری مطمئن هستید؟ </h5>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image.ImageName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Image.ImageName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image.CreateDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Image.CreateDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image.Gallery)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Image.Gallery.GalleryName)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Image.ImageId" />
        <input type="submit" value="حذف" class="btn btn-danger" />
        <a asp-page="./Index" class="btn btn-default"> بازگشت به لیست </a>
    </form>
</div>

Pages/Admin/Image/Edit.cshtml
@page
@model GharchNews.Pages.Admin.Image.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Image.ImageId" />
            <div class="form-group">
                <label asp-for="Image.ImageName" class="control-label"></label>
                <input asp-for="Image.ImageName" class="form-control" />
                <span asp-validation-for="Image.ImageName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image.CreateDate" class="control-label"></label>
                <input asp-for="Image.CreateDate" class="form-control" />
                <span asp-validation-for="Image.CreateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image.GalleryId" class="control-label"></label>
                <select asp-for="Image.GalleryId" class="form-control" asp-items="ViewBag.GalleryId"></select>
                <span asp-validation-for="Image.GalleryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="ویرایش" class="btn btn-warning" />
                <a asp-page="./Index" class="btn btn-default"> بازگشت به لیست </a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Admin/Image/Index.cshtml
@page
@model GharchNews.Pages.Admin.Image.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_AdminLayout.cshtml";
}

<hr />
<p>
    <a asp-page="Create" class="btn btn-success"> افزودن عکس </a>
</p>
<hr />

@if (ViewBag.CurrentGallery != null)
{
    <a asp-page="../Gallery/Index" class="btn btn-primary"> بازگشت به گالری ها <i class="fa fa-list" style="font-size:14px; color:black"></i> </a>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Images[0].ImageName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Images[0].CreateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Images[0].Gallery)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Images)
        {
            <tr>
                <td>
                    @if (ViewBag.CurrentGallery == null)
                    {
                        @foreach (var gallery in ViewBag.Galleries)
                        {
                            @if (item.Gallery.GalleryName == gallery)
                            {
                                <img src="/Img/GalleryImages/@gallery/@Html.DisplayFor(modelItem => item.ImageName)" style="max-width:60px" class="img-thumbnail" />
                            }
                        }
                    }
                    else
                    {
                        <img src="/Img/GalleryImages/@ViewBag.CurrentGallery/@Html.DisplayFor(modelItem => item.ImageName)" style="max-width:60px" class="img-thumbnail" />
                    }

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gallery.GalleryName)
                </td>
                <td>
                    <a asp-page="Edit" asp-route-id="@item.ImageId"><i class="fa fa-edit" style="color:darkorange;font-size:20px"></i></a>
                    <a asp-route-id="@item.ImageId" asp-page-handler="Delete" asp-route-ReturnUrl="@ViewBag.CurrentGallery"><i class="fa fa-trash" style="color:red;font-size:20px"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (ViewBag.CurrentGallery != null)
{
    <a asp-page="../Image/Index" class="btn btn-warning"> نمایش تمام عکس ها </a>
}